openapi: 3.0.1

info:
  title: INIPEC-lookupPEC
  description: "API restituisce la PEC registrata in INI-PEC relativa ad un'impresa o libero professionista.
                L'autenticazione tra fruitore ed erogatore è assicurata dall'utilizzo del TLS mutual authentication
                
                ModI patterns applied:
                  - CRUD_REST
                  - ID_AUTH_CHANNEL_02
                  - INTEGRITY_REST_01
                "
  version: 1.0.0

servers:
- url: https://www.inipec.gov.it/lookuppec/rest/v1.0.0


paths:
  /{cf}:
    get:
      parameters:
      - name: cf
        in: path
        description: cf dell'impresa o del libero professionista
        required: true
        schema:
          pattern: ^([A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z])|(\d{11})$
          type: string
      responses:
        200:
          description: OK
          headers:
            Agid-JWT-Signature:
              description: "JWT utilizzato per validare la firma del payload
                               1. il Jose Header con almeno i parameter:
                                  - alg con l’algoritmo di firma
                                  - typ uguale a JWT
                                  - una o più delle seguenti opzioni per referenziare il certificato X.509:
                                    - x5u (X.509 URL)
                                    - x5c (X.509 Certificate Chain)
                                    - x5t#256 (X.509 Certificate SHA-256 Thumbprint)
                                2. i seguenti claim obbligatori:
                                   - i riferimenti temporali di emissione e scadenza: iat , exp. Se il flusso richiede di verificare l’istante di prima validità del token, si può usare il claim nbf
                                   - il riferimento dell’erogatore in aud
                                3. i seguenti claim, secondo la logica del servizio:
                                  - Digest
                                  - Content-Type
                                  - Content-Encoding" 
                                
              schema:
                $ref: '#/components/headers/AgidJWTSignatureHeader'
            Digest:
              description: digest del payload firmato 
              schema:
                $ref: '#/components/headers/DigestHeader'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PECvalue'
        400:
          description: "BAD REQUEST: \n
                        - type: www.inipec.gov.it/errorcode/badpath, title: errore del path, detail: /{cd}, status:400"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        404:
          description: "NOT FOUND: \n
                        - type: www.inipec.gov.it/errorcode/domain.notfound, title: {cf} not found, status:404"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  headers:
    AgidJWTSignatureHeader:
      description: header contenete JWT per la verifica della firma
      schema:
          $ref: '#/components/schemas/AgidJWSSignatureHeader' 
    DigestHeader:
      description: header contenete digest della firma
      schema:
          $ref: '#/components/schemas/DigestHeader'

  schemas:
    PECvalue:
      required:
      - cf
      - email
      - denominazione
      type: object
      properties:
        cf:
          type: string
          description: cf utilizzato per il lookup della PEC e della denominazione
          pattern: ^([A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z])|(\d{11})$          
        email:
          type: string
          description: PEC presente in INI-PEC per l'indicato cf
          format: email
        denominazione:
          type: string
          description: denominazione dell'impresa o libero professionistra per l'indicato cf
      example:
        cf: 12345678901
        esito: 12345678901@pec.it 
        tipo: denominazione 12345678901

    AgidJWSSignatureHeader:
      type: string
      pattern:  ^([0-9a-zA-Z+/]{4})*(([0-9a-zA-Z+/]{2}==)|([0-9a-zA-Z+/]{3}=))?.([0-9a-zA-Z+/]{4})*(([0-9a-zA-Z+/]{2}==)|([0-9a-zA-Z+/]{3}=))?.([0-9a-zA-Z+/]{4})*(([0-9a-zA-Z+/]{2}==)|([0-9a-zA-Z+/]{3}=))?$
      example:
        eyJhbGciOiJQUzM4NCIsImtpZCI6ImJpbGJvLmJhZ2dpbnNAaG9iYml0b24uZXhhbXBsZSJ9.SXTigJlzIGEgZGFuZ2Vyb3VzIGJ1c2luZXNzLCBGcm9kbywgZ29pbmcgb3V0IHlvdXIgZG9vci4gWW91IHN0ZXAgb250byB0aGUgcm9hZCwgYW5kIGlmIHlvdSBkb24ndCBrZWVwIHlvdXIgZmVldCwgdGhlcmXigJlzIG5vIGtub3dpbmcgd2hlcmUgeW91IG1pZ2h0IGJlIHN3ZXB0IG9mZiB0by4.cu22eBqkYDKgIlTpzDXGvaFfz6WGoz7fUDcfT0kkOy42miAh2qyBzk1xEsnk2IpN6-tPid6VrklHkqsGqDqHCdP6O8TTB5dDDItllVo6_1OLPpcbUrhiUSMxbbXUvdvWXzg-UD8biiReQFlfz28zGWVsdiNAUf8ZnyPEgVFn442ZdNqiVJRmBqrYRXe8P_ijQ7p8Vdz0TTrxUeT3lm8d9shnr2lfJT8ImUjvAA2Xez2Mlp8cBE5awDzT0qI0n6uiP1aCN_2_jLAeQTlqRHtfa64QQSUmFAAjVKPbByi7xho0uTOcbH510a6GYmJUAfmWjwZ6oD4ifKo8DYM-X72Eaw

    DigestHeader:
      type: string
      pattern: ^(S256|S384|S512)=([0-9a-zA-Z+/]{4})*(([0-9a-zA-Z+/]{2}==)|([0-9a-zA-Z+/]{3}=))?.([0-9a-zA-Z+/]{4})*(([0-9a-zA-Z+/]{2}==)|([0-9a-zA-Z+/]{3}=))?.([0-9a-zA-Z+/]{4})*(([0-9a-zA-Z+/]{2}==)|([0-9a-zA-Z+/]{3}=))?$
      example:
        S256=cFfTOCesrWTLVzxn8fmHl4AcrUs40Lv5D275FmAZ96E

    Error:
      required:
      - status
      - title
      - type
      type: object
      properties:
        type:
          type: string
          description: uri che identifica il problema
          format: uri
        title:
          type: string
          description: Breve descrizione dello specifico problema verificatosi
        detail:
          type: string
          description: Descrizione di dettaglio dello specifico problema verificatosi
        status:
          maximum: 600
          minimum: 100
          type: integer
          description: HTTP status code generato dal server
          format: int32
      example:
        type: www.inipec.gov.it/errorcode/badpath
        title: errore del path
        detail: path atteso /{cf}
        status: 400